modLoader="javafml"
loaderVersion="[43,)"
license="MIT License"

[[mods]]
modId="avaritia"
version="0.5.2"
displayName="Avaritia Reset Version"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
logoFile="logo.png"
authors="IAD Studio, Jin1358, MCreator"
description='''
Avaritia mod high version reset version
'''

[[dependencies.avaritia]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2]"
    ordering="NONE"
    side="BOTH"




